name: Build and Push Vite React App with Podman

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GHCR_USER: ${{ github.repository_owner }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version

      - name: Build Podman Image
        run: |
          USERNAME=$(echo $GHCR_USER | tr '[:upper:]' '[:lower:]')
          podman build --log-level debug -t ghcr.io/$USERNAME/vite-podman-demo:${GITHUB_SHA} .

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image
        run: |
          USERNAME=$(echo $GHCR_USER | tr '[:upper:]' '[:lower:]')
          podman push ghcr.io/$USERNAME/vite-podman-demo:${GITHUB_SHA}
